/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexGramSchmidt
public import HexMatrix.Lattice

public section

/-!
Integer row-lattice membership and independence for `hex-lll`,
with the row-operation lemmas showing that an adjacent swap or a
size-reduction row combination preserves the generated lattice.
-/

namespace Hex

namespace Matrix

/-- The rows of `b` are linearly independent, witnessed by positivity of each
executable leading Gram determinant. -/
@[expose]
def independent (b : Matrix Int n m) : Prop :=
  GramSchmidt.Int.independent b

/-- Independence is decidable (via `GramSchmidt.Int.independent`), so it can be
tested at runtime. -/
instance (b : Matrix Int n m) : Decidable (independent b) :=
  inferInstanceAs (Decidable (GramSchmidt.Int.independent b))

end Matrix

namespace Internal

open Hex.Matrix

/-- `memLattice_of_rowSwap_memLattice` states that any vector in the lattice
generated by `rowSwap b i j` also lies in the lattice generated by `b`. -/
theorem memLattice_of_rowSwap_memLattice
    (b : Matrix Int n m) (i j : Fin n) (v : Vector Int m) :
    Matrix.memLattice (Matrix.rowSwap b i j) v → Matrix.memLattice b v := by
  intro hv
  rcases hv with ⟨c, hc⟩
  let S : Matrix Int n n := Matrix.rowSwap (Matrix.identity (R := Int) n) i j
  have hrow : S * b = Matrix.rowSwap b i j := by
    rw [Matrix.rowSwap_mul, Matrix.identity_mul]
  refine ⟨Matrix.transpose S * c, ?_⟩
  calc
    Matrix.vecMul (Matrix.transpose S * c) b
        = Matrix.transpose b * (Matrix.transpose S * c) := rfl
    _ = (Matrix.transpose b * Matrix.transpose S) * c := by
      rw [Matrix.mul_assoc_vec]
    _ = Matrix.transpose (S * b) * c := by
      rw [Matrix.transpose_mul_of_mul_comm]
    _ = Matrix.transpose (Matrix.rowSwap b i j) * c := by
      rw [hrow]
    _ = Matrix.vecMul c (Matrix.rowSwap b i j) := rfl
    _ = v := hc

/-- `rowSwap_memLattice_iff` states that swapping rows `i` and `j` of `b`
preserves lattice membership in both directions. -/
theorem rowSwap_memLattice_iff
    (b : Matrix Int n m) (i j : Fin n) (v : Vector Int m) :
    Matrix.memLattice (Matrix.rowSwap b i j) v ↔ Matrix.memLattice b v := by
  constructor
  · exact memLattice_of_rowSwap_memLattice b i j v
  · intro hv
    have hv' : Matrix.memLattice (Matrix.rowSwap (Matrix.rowSwap b i j) i j) v := by
      rwa [Matrix.rowSwap_rowSwap]
    exact memLattice_of_rowSwap_memLattice (Matrix.rowSwap b i j) i j v hv'

/-- `memLattice_of_rowAdd_memLattice` states that any vector in the lattice
generated by `rowAdd b src dst c` also lies in the lattice generated by `b`. -/
theorem memLattice_of_rowAdd_memLattice
    (b : Matrix Int n m) (src dst : Fin n) (c : Int) (v : Vector Int m) :
    Matrix.memLattice (Matrix.rowAdd b src dst c) v → Matrix.memLattice b v := by
  intro hv
  rcases hv with ⟨w, hw⟩
  let S : Matrix Int n n := Matrix.rowAdd (Matrix.identity (R := Int) n) src dst c
  have hrow : S * b = Matrix.rowAdd b src dst c := by
    simp [S, Matrix.rowAdd_mul, Matrix.identity_mul]
  refine ⟨Matrix.transpose S * w, ?_⟩
  calc
    Matrix.vecMul (Matrix.transpose S * w) b
        = Matrix.transpose b * (Matrix.transpose S * w) := rfl
    _ = (Matrix.transpose b * Matrix.transpose S) * w := by
      rw [Matrix.mul_assoc_vec]
    _ = Matrix.transpose (S * b) * w := by
      rw [Matrix.transpose_mul_of_mul_comm]
    _ = Matrix.transpose (Matrix.rowAdd b src dst c) * w := by
      rw [hrow]
    _ = Matrix.vecMul w (Matrix.rowAdd b src dst c) := rfl
    _ = v := hw

/-- `rowAdd_memLattice_iff` states that adding `c` times row `src` to a distinct
row `dst` of `b` preserves lattice membership in both directions. -/
theorem rowAdd_memLattice_iff
    (b : Matrix Int n m) {src dst : Fin n} (hne : src ≠ dst) (c : Int) (v : Vector Int m) :
    Matrix.memLattice (Matrix.rowAdd b src dst c) v ↔ Matrix.memLattice b v := by
  constructor
  · exact memLattice_of_rowAdd_memLattice b src dst c v
  · intro hv
    have hv' : Matrix.memLattice
        (Matrix.rowAdd (Matrix.rowAdd b src dst c) src dst (-c)) v := by
      rwa [Matrix.rowAdd_rowAdd_neg b c hne]
    exact memLattice_of_rowAdd_memLattice (Matrix.rowAdd b src dst c) src dst (-c) v hv'

end Internal

end Hex
